apiVersion: apps/v1
kind: Deployment
metadata:
  name: hey-deployment
  labels:
    app: hey
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hey
  template:
    metadata:
      labels:
        app: hey
    spec:
      containers:
        - name: hey-container
          image: mokshith369/hey-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 55001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false